In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
os.chdir("E:\Machine LEARNING\Datasets")


In [3]:
df=pd.read_csv('data.csv')

In [4]:
df.head(5)

URLs  \
0  http://www.bbc.com/news/world-us-canada-414191...   
1  https://www.reuters.com/article/us-filmfestiva...   
2  https://www.nytimes.com/2017/10/09/us/politics...   
3  https://www.reuters.com/article/us-mexico-oil-...   
4  http://www.cnn.com/videos/cnnmoney/2017/10/08/...   

                                            Headline  \
0         Four ways Bob Corker skewered Donald Trump   
1  Linklater's war veteran comedy speaks to moder...   
2  Trump’s Fight With Corker Jeopardizes His Legi...   
3  Egypt's Cheiron wins tie-up with Pemex for Mex...   
4        Jason Aldean opens 'SNL' with Vegas tribute   

                                                Body  Label  
0  Image copyright Getty Images\nOn Sunday mornin...      1  
1  LONDON (Reuters) - “Last Flag Flying”, a comed...      1  
2  The feud broke into public view last week when...      1  
3  MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...      1  
4  Country singer Jason Aldean, who was performin...      1

In [27]:
#cleaning and processing data

In [5]:
df.isnull().sum()

URLs         0
Headline     0
Body        21
Label        0
dtype: int64

In [29]:
#df.dropna(inplace=True)

In [30]:
#df.reset_index(inplace=True,drop=False)

In [6]:
df.isnull().sum()

URLs         0
Headline     0
Body        21
Label        0
dtype: int64

In [7]:
df.columns

Index(['URLs', 'Headline', 'Body', 'Label'], dtype='object')

In [8]:
import re
import nltk

In [34]:
#nltk.download('stopwords')

In [9]:
from nltk.corpus import stopwords

In [10]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [37]:
#df.drop(['URLs'],inplace=True,axis=1)

In [38]:
#df.reset_index(inplace=True,drop=False)

In [11]:
df.head(2)

URLs  \
0  http://www.bbc.com/news/world-us-canada-414191...   
1  https://www.reuters.com/article/us-filmfestiva...   

                                            Headline  \
0         Four ways Bob Corker skewered Donald Trump   
1  Linklater's war veteran comedy speaks to moder...   

                                                Body  Label  
0  Image copyright Getty Images\nOn Sunday mornin...      1  
1  LONDON (Reuters) - “Last Flag Flying”, a comed...      1

In [40]:
df[ 'Headline'][159]

"Las Vegas massacre: How a stranger saved a woman's life"

In [12]:
corpus=[]
for i in range(0, len(df)):
  a=re.sub('[^a-zA-Z]',' ', df['Headline'][i])
  a=a.lower()
  a=a.split()
  a=[ps.stem(word) for word in a if not  word in stopwords.words('english')]
  a=' '.join(a)
  corpus.append(a)

In [13]:
corpus

['four way bob corker skewer donald trump',
 'linklat war veteran comedi speak modern america say star',
 'trump fight corker jeopard legisl agenda',
 'egypt cheiron win tie pemex mexican onshor oil field',
 'jason aldean open snl vega tribut',
 'jetnat fanduel leagu week',
 'kansa tri tax plan similar trump fail',
 'india rbi chief growth import cost inflat newspap',
 'epa chief sign rule clean power plan exit tuesday',
 'talk sale air berlin plane easyjet risk collaps report',
 'u presid donald trump quietli sign law allow warrantless search part va dc md',
 'fantasi footbal team defens rank week',
 'shut play damn basebal',
 'deloitt cyber attack affect client guardian',
 'chuck axe hbd brickyard adam moonlight ace chuck season final',
 'gunman girlfriend said know plan harm',
 'maril danley gunman girlfriend say unawar plan',
 'trump immigr rhetor echo bitter fight',
 'trump bemoan littl appreci san juan mayor beg water',
 'meet militari trump talk calm storm',
 'teacher spark outr

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
cv=CountVectorizer()

In [16]:

y=df.iloc[:,-1]

In [18]:
x=cv.fit_transform(corpus).toarray()

In [19]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.20,random_state=0)

In [22]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [50]:
#df.drop([156],inplace=True,axis=0)

In [24]:
y_pred=model.predict(x_test)

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix(y_test,y_pred)

array([[359,  74],
       [ 31, 338]], dtype=int64)

In [28]:
accuracy_score(y_test,y_pred)

0.8690773067331671

In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.83      0.87       433
           1       0.82      0.92      0.87       369

    accuracy                           0.87       802
   macro avg       0.87      0.87      0.87       802
weighted avg       0.87      0.87      0.87       802



In [31]:
from sklearn.naive_bayes import  MultinomialNB

In [32]:
model2=MultinomialNB()

In [33]:
model2.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [34]:
y_pred=model2.predict(x_test)

In [35]:
confusion_matrix(y_test,y_pred)

array([[363,  70],
       [ 46, 323]], dtype=int64)

In [36]:
accuracy_score(y_test,y_pred)

0.8553615960099751

In [37]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.84      0.86       433
           1       0.82      0.88      0.85       369

    accuracy                           0.86       802
   macro avg       0.85      0.86      0.86       802
weighted avg       0.86      0.86      0.86       802

